namespace DPong.Level.State {
  struct ScoresState {
    int Left;
    int Right;
  }

  struct BallState {
    FxNum FreezeCooldown;
    FxVec2 Speed;
    FxVec2 Position;
  }

  struct BlockerState {
    FxVec2 Position;
  }

  array BlockerState2 BlockerState[2];

  struct LevelState {
    FxNum Pace;
    ScoresState Scores;
    FxRandomState Random;
    BallState Ball;
    BlockerState2 Blockers;
  }
}