namespace DPong.Level.State {
  struct ScoresState {
    int Left;
    int Right;
  }

  struct BallState {
    FxNum FreezeCooldown;
    FxVec2 Speed;
    FxVec2 Position;
  }

  struct PaddleState {
    FxVec2 Position;
  }

  array PaddleState2 PaddleState[2];

  struct LevelState {
    FxNum Pace;
    ScoresState Scores;
    FxRandomState Random;
    BallState Ball;
    PaddleState2 Paddles;
  }
}